import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jesse Robinson | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {Array.from(Array(1000).keys()).map((n) => (
        <h1 key={n + 1}>amy is a bitch hoe</h1>
      ))}
      <p>
        jk she bae and she high key sexy and sweet and funny and cool and i luv
        her
      </p>
    </div>
  );
}
