#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# npm test
yarn format
git add -A
echo "$(tput setaf 2)Wake up....."
echo "$(tput setaf 2)The Matrix has you......"
echo "$(tput setaf 2)Follow the white rabbit......"
